tk_4_basdat/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('acara/',include('acara.urls')),
    path('penugasan/',include('penugasan.urls')),
    path('stasiun/',include('stasiun.urls')),
    path('sepeda/',include('sepeda.urls')),
    path('user/',include('user.urls')),
    path('voucher/',include('voucher.urls')),
    path('transaksi/',include('transaksi.urls')),
    
    

]

user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views



app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
	path('registerAnggota/', views.registerAnggota, name='registerAnggota'),
	path('registerPetugas/', views.registerPetugas, name='registerPetugas'),
    
]


user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.db import connection
from django.urls import reverse
from django.contrib import messages
from random import randint
from django.http import HttpResponseRedirect


# Create your views here.

def login(request):
	if('nama' in request.session.keys()):
		return HttpResponseRedirect('/')
		
	return render(request,'login.html')
	
def logout(request):
	request.session.flush()
	return HttpResponseRedirect('/')


def registerAnggota(request):
	return render(request,'registerAnggota.html')


def registerPetugas(request):
	return render(request,'registerPetugas.html')

user/templates/login.html
{% extends 'baseacara.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<div class="col-lg-6">

    <div class="form">
      
      <h4>Form Login</h4>
      <form action="" method="post" role="form" class="contactForm">
        <div class="form-group">
          <input type="text" name="name" class="form-control" id="name" placeholder="No KTP" data-rule="minlen:4" data-msg="Masukan no KTP" />
          <div class="validation"></div>
        </div>
        <div class="form-group">
            <input type="text" name="name" class="form-control" id="name" placeholder="Email" data-rule="minlen:4" data-msg="Masukan Email" />
            <div class="validation"></div>
          </div>

		<button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Login</button>
                  <div class="text-center">
                    <a class="small" href="{% url 'user:registerAnggota' %}">SIGN UP Anggota</a><br>
					<a class="small" href="{% url 'user:registerPetugas' %}">SIGN UP Petugas</a></div>
					
		</form>

    {% endblock content %}

user/templates/registerAnggota.html
{% extends 'baseacara.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<div class="col-lg-6">

    <div class="form">
      
      <h4>Form Pendaftaran Pengguna</h4>
      <form action="/User/registerAnggota/" method="POST" role="form" class="contactForm">
	  {% csrf_token %}
        <div class="form-group">
          <input type="text" name="ktp" class="form-control" id="ktp" placeholder="No KTP" data-rule="minlen:4" data-msg="Masukan no KTP" />
          <div class="validation"></div>
        </div>
        <div class="form-group">
            <input type="text" name="name" class="form-control" id="name" placeholder="Nama Lengkap" data-rule="minlen:4" data-msg="Masukan Nama Lengkap" />
            <div class="validation"></div>
          </div>
		<div class="form-group">
          <input type="text" name="email" class="form-control" id="email" placeholder="Email" data-rule="minlen:4" data-msg="Masukan Email" />
          <div class="validation"></div>
        </div>
		<div class="form-group">
          <input type="text" name="ttl" class="form-control" id="ttl" placeholder="Tanggal Lahir" data-rule="minlen:4" data-msg="Masukan Tanggal lahir" />
          <div class="validation"></div>
        </div>
		<div class="form-group">
          <input type="text" name="notlp" class="form-control" id="notlp" placeholder="No Telepon" data-rule="minlen:4" data-msg="Masukan No telepon" />
          <div class="validation"></div>
        </div>
		<div class="form-group">
          <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat" data-rule="minlen:4" data-msg="Masukan Alamat" />
          <div class="validation"></div>
        </div>
		
		<button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Sign Up</button>
		
		</form>
    

    {% endblock content %}

user/templates/registerPetugas.html
{% extends 'baseacara.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<div class="col-lg-6">

    <div class="form">
      
      <h4>Form Pendaftaran Pengguna</h4>
      <form action="" method="post" role="form" class="contactForm">
        <div class="form-group">
          <input type="text" name="ktp" class="form-control" id="ktp" placeholder="No KTP" data-rule="minlen:4" data-msg="Masukan no KTP" />
          <div class="validation"></div>
        </div>
        <div class="form-group">
            <input type="text" name="name" class="form-control" id="name" placeholder="Nama Lengkap" data-rule="minlen:4" data-msg="Masukan Nama Lengkap" />
            <div class="validation"></div>
          </div>
		<div class="form-group">
          <input type="text" name="email" class="form-control" id="email" placeholder="Email" data-rule="minlen:4" data-msg="Masukan Email" />
          <div class="validation"></div>
        </div>
		<div class="form-group">
          <input type="text" name="ttl" class="form-control" id="ttl" placeholder="Tanggal Lahir" data-rule="minlen:4" data-msg="Masukan Tanggal lahir" />
          <div class="validation"></div>
        </div>
		<div class="form-group">
          <input type="text" name="notlp" class="form-control" id="notlp" placeholder="No Telepon" data-rule="minlen:4" data-msg="Masukan No telepon" />
          <div class="validation"></div>
        </div>
		<div class="form-group">
          <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat" data-rule="minlen:4" data-msg="Masukan Alamat" />
          <div class="validation"></div>
        </div>
		<div class="form-group">
          <input type="text" name="gaji" class="form-control" id="gaji" placeholder="Gaji" data-rule="minlen:4" data-msg="Masukan Gaji" />
          <div class="validation"></div>
        </div>
		
		<button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Sign Up</button>
		
		</form>
    

    {% endblock content %}