sepeda/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name = 'sepeda'
urlpatterns = [
    path('create',views.sepedacreate, name ='sepedacreate'),
    path('list',views.sepedalist, name ='sepedalist'),

]

tk_4_basdat/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('acara/',include('acara.urls')),
    path('penugasan/',include('penugasan.urls')),
    path('stasiun/',include('stasiun.urls')),
    path('sepeda/',include('sepeda.urls')),
    path('user/',include('user.urls')),
    path('voucher/',include('voucher.urls')),
    path('transaksi/',include('transaksi.urls')),
    
    

]

transaksi/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name = 'transaksi'
urlpatterns = [
    path('transaksi/',views.transaksi, name ='transaksi'),
	path('laporan/',views.laporan, name ='laporan'),
	path('topup/',views.topup, name ='topup'),
	path('post-topup/',views.topupfunc, name='topupfunc'),
]

user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views



app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
	path('registerAnggota/', views.registerAnggota, name='registerAnggota'),
	path('registerPetugas/', views.registerPetugas, name='registerPetugas'),
    
]


sepeda/models.py
from django.db import models

# Create your models here.

sepeda/views.py
from django.shortcuts import render
from django.db import connection

# Create your views here.
def sepedacreate(request):
    return render(request, 'sepeda.html')

def sepedalist(request):
    
    response={}
    cursor = connection.cursor()
    cursor.execute('set search_path to bike_station,bike_sharing')
    cursor.execute("select * from sepeda;")

    hasil1 = cursor.fetchall()
    response['sepeda'] = hasil1
   

 
    return render(request, 'listsepeda.html',response)

sepeda/templates/basesepeda.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Sepeda</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'bootstrap/Rapid/img/title.jpg' %}" rel="icon">
  <link href="{% static 'bootstrap/Rapid/img/title.jpg' %}" rel="apple-touch-icon">
  
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'bootstrap/Rapid/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'bootstrap/Rapid/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'bootstrap/Rapid/lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'bootstrap/Rapid/lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'bootstrap/Rapid/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'bootstrap/Rapid/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">


  <!-- Main Stylesheet File -->
  <link href="{% static 'bootstrap/Rapid/css/style.css' %}" rel="stylesheet">


  <!-- =======================================================
    Theme Name: Rapid
    Theme URL: https://bootstrapmade.com/rapid-multipurpose-bootstrap-business-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body>
  <!--==========================
  Header
  ============================-->
  <header id="header">

      <div id="topbar">
        <div class="container">
          <div class="social-links">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
          </div>
        </div>
      </div>
  
      <div class="container">
  
        <div class="logo float-left">
          <!-- Uncomment below if you prefer to use an image logo -->
          <h1 class="text-light"><a href="/" class="scrollto"><span>Bike Sharing</span></a></h1>
          <!-- <a href="#header" class="scrollto"><img src="img/logo.png" alt="" class="img-fluid"></a> -->
        </div>
  
        <nav class="main-nav float-right d-none d-lg-block">
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/#about">About Us</a></li>
            <li><a href="{% url 'user:login' %}">Login</a></li>
            <li><a href="/#team">Team</a></li>
            <li class="drop-down"><a href="/#services">Kegiatan Bike Sharing</a>
              <ul>
                <li class="drop-down"><a href="#">Transaksi</a>
                  <ul>
                    <li><a href="{% url 'transaksi:topup' %}">Top Up</a></li>
                    <li><a href="{% url 'transaksi:laporan' %}">Daftar laporan</a></li>
                    <li><a href="{% url 'transaksi:transaksi' %}">Riwayat Transaksi</a></li>
                  </ul>
                </li>
                <li class="drop-down"><a href="#">Acara</a>
                  <ul>
                    <li><a href="/acara/create">Create</a></li>
                    <li><a href="/acara/list">List of event</a></li>
                  </ul>
                </li>
                <li class="drop-down"><a href="#">Penugasan</a>
                  <ul>
                    <li><a href="/penugasan/create">Create</a></li>
                    <li><a href="/penugasan/list">List of duties</a></li>
                  </ul>
                </li>
                <li class="drop-down"><a href="#">Sepeda</a>
                  <ul>
                    <li><a href="/sepeda/create">Create</a></li>
                    <li><a href="/sepeda/list">List of bike</a></li>
                  </ul>
                </li>
                <li class="drop-down"><a href="#">Stasiun</a>
                  <ul>
                    <li><a href="/stasiun/create">Create</a></li>
                    <li><a href="/stasiun/list">List of station</a></li>
                  </ul>
                </li>
                <li class="drop-down"><a href="#">Voucher</a>
                  <ul>
                    <li><a href="/voucher/add">Add voucher</a></li>
                    <li><a href="/voucher/update">Update voucher</a></li>
                    <li><a href="/voucher/dafcer">List voucher</a></li>
                  </ul>
                </li>
                <li class="drop-down"><a href="#">Peminjaman</a>
                  <ul>
                    <li><a href="/voucher/pinjam">Peminjaman</a></li>
                    <li><a href="/voucher/dafjem">List of peminjaman</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li><a href="/#footer">Contact Us</a></li>
          </ul>
        </nav><!-- .main-nav -->
        
      </div>
    </header><!-- #header -->

  {% block content %}
	{% endblock %}

  <!--==========================
    Footer
  ============================-->
  <footer id="footer" class="section-bg">
      <div class="footer-top">
        <div class="container">
  
          <div class="row">
  
            <div class="col-lg-6">
  
              <div class="row">
  
                  <div class="col-sm-6">
  
                    <div class="footer-info">
                      <h3>Bike Sharing</h3>
                      <p>Blablablaba</p>
                    </div>
  
                    
  
                  </div>
  
                  <div class="col-sm-6">
                    <div class="footer-links">
                      <h4>Useful Links</h4>
                      <ul>
                        <li><a href="/">Home</a></li>
                        <li><a href="/">About us</a></li>
                        <li><a href="/">Kegiatan Bike Sharing</a></li>
                        
                      </ul>
                    </div>
  
                    <div class="footer-links">
                      <h4>Contact Us</h4>
                      <p>
                        Fasilkom UI
                      </p>
                    </div>
  
                    <div class="social-links">
                      <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                      <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                      <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                      <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                    </div>
  
                  </div>
  
              </div>
  
            </div>
  
          </div>
  
        </div>
      </div>
  
      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong>Beloved Team</strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Rapid
          -->
          Designed with love
        </div>
      </div>
    </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- JavaScript Libraries -->
  
  <script href="{% static 'bootstrap/Rapid/lib/jquery/jquery.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/jquery/jquery-migrate.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/easing/easing.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/mobile-nav/mobile-nav.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/wow/wow.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/waypoints/waypoints.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/counterup/counterup.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/isotope/isotope.pkgd.min.js' %}"></script>
  <script href="{% static 'bootstrap/Rapid/lib/lightbox/js/lightbox.min.js' %}"></script>

  <!-- Contact Form JavaScript File -->
  <script href="{% static 'bootstrap/Rapid/contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script href="{% static 'bootstrap/Rapid/js/main.js' %}"></script>

</body>
</html>

sepeda/templates/listsepeda.html
{% extends 'basesepeda.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<table class="table table-hover table-dark">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Merk</th>
        <th scope="col">Jenis</th>
        <th scope="col">Stasiun</th>
        <th scope="col">Status</th>
        <th scope="col">Penyumbang</th>
        <th scope="col">Action(Admin Only)</th>
        <th scope="col">Action(Anggota Only)</th>
      </tr>
    </thead>
    <tbody>
      {%for i in sepeda%}
      <tr>
          <th scope="row">{{i.0}}</th>
          <th>{{i.1}}</th>
          <td>{{i.2}}</td>
          <td>{{i.4}}</td>
          <td>{{i.3}}</td>
          <td>{{i.5}}</td>
        <td>
            <button type="button" class="btn btn-primary disabled" >Update</button> OR <button type="button" class="btn btn-primary disabled" >Delete</button>
        </td>
        <td>
                <button type="button" class="btn btn-primary disabled" >Pinjam</button>
            </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>



{% endblock content %}

sepeda/templates/sepeda.html
{% extends 'basesepeda.html' %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<div class="col-lg-6">

    <div class="form">
      
      <h4>Daftarkan Sepeda</h4>
      <form action="" method="post" role="form" class="contactForm">
        <div class="form-group">
          <input type="text" name="name" class="form-control" id="name" placeholder="Merk" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
          <div class="validation"></div>
        </div>
        <div class="form-group">
            <input type="text" name="name" class="form-control" id="name" placeholder="Jenis" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
            <div class="validation"></div>
          </div>
        <label for="country">Status</label>
          <select id="country" name="country">
            <option value="iya">Tersedia</option>
            <option value="tidak">Tidak Tersedia</option>
          </select>
        <label for="country">Stasiun</label>
          <select id="country" name="country">
              <option value="volvo">pocin</option>
              <option value="saab">kutek</option>
              <option value="opel">fh</option>
              <option value="audi">balairung</option>
            </select>
        <label for="country">Penyumbang</label>
          <select id="country" name="country">
            <option value="iya">idris</option>
            <option value="tidak">yoga</option>
          </select>

        <div id="sendmessage">Your message has been sent. Thank you!</div>
        <div id="errormessage"></div>

        <div class="text-center"><a type="submit" title="Send Message" href ="\sepeda\list">Send Message</a></div>
      </form>
    </div>


    

    {% endblock content %}